database:
  server: localhost
  port: 27017
  dbName: movies

# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9090

logging:
  level: INFO

  appenders:
    - type: console